# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  OnlyOfficeTestCallback:
    UUID: 1c77304b-277e-40a7-91ca-57cdac099b58
    Url: '{ivy.app.baseurl}/api/'
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
